### ISSUE TITLE
CA state assembly/senate members not shown for my address

### ISSUE THREAD

**Issue by rmtheis** [sankarravi/yimbyscorecard#7]
The link I used:

https://sankarravi.github.io/yimbyscorecard/list#san%20luis%20obispo%2C%20CA%2093401

I also tried a couple of street addresses in San Luis Obispo.

I was expecting state-level legislator info but didn't see anything about state senate/assembly reps there.

**Comment by sankarravi** [comment]
@rmtheis The underlying API we're using (the Google Civic API) seems to generally only return state-level reps if you have a specific street address with a residential zoning... which kind of confuses me since _most_ zipcodes are probably not split across districts.

E.g., https://whoaremyrepresentatives.org/representatives?address=san+luis+obispo&zip=93401 pulls from the same data and is also missing these.

The street addresses kind of surprise me though. If you find any addresses that are returned by whoaremyrepresentatives but not by this tool, please let me know!

**Comment by rmtheis** [comment]
Thanks for the clarification! Yes, after taking a second look with your comments in mind, this project does seem to be working as intended.

Thank you for the excellent project!
